name: Проверка CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  lint:
    name: Проверка стиля (pylint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Установка pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Запуск pylint (проверка файлов)
        run: |
          pylint currency_converter.py cli.py

  test:
    name: Запуск тестов (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Установка pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Запуск pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
